// Command docgen generates the Starlight command reference for the docs
// site from the live cobra tree (cli.NewRootCmd): one page per available
// top-level command (subcommands become sections on that page), an
// index.md overview table, and global-flags.md. `make docs-reference` runs
// it; `make docs-reference-check` regenerates and fails on any diff, so the
// committed reference can never drift from the binary.
//
// Output is deterministic: commands and flags are walked in cobra's sorted
// order, nothing time- or host-dependent is emitted, BRONTO_* environment
// variables are cleared before the tree is built, and any machine-specific
// string that still leaks into help text or flag defaults (home directory,
// temp dir, user config/cache dir) is replaced with a stable placeholder.
// (Bare host or user names are deliberately not replaced: a short name
// like "user" would also rewrite ordinary words, differently per machine.)
//
// "Learn more" links come from a hand-maintained YAML map (command path
// without the leading "bronto" -> docs.bronto.io URL). An entry naming a
// command that does not exist fails the run, so the map cannot rot.
//
// Usage (from the repo root):
//
//	go run ./internal/tools/docgen [-out dir] [-links file]
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
	"gopkg.in/yaml.v3"

	"github.com/bronto-community/bronto-cli/internal/cli"
)

const (
	defaultOut   = "docs/src/content/docs/reference/commands"
	defaultLinks = "docs/reference-links.yaml"
	// urlBase is where the generated pages are served on the site.
	urlBase         = "/reference/commands/"
	globalFlagsSlug = "global-flags"
	generatedNotice = "<!-- Generated by internal/tools/docgen from the cobra command tree. DO NOT EDIT: run `make docs-reference`. -->"
)

func main() {
	out := flag.String("out", defaultOut, "output directory for the generated pages")
	links := flag.String("links", defaultLinks, "YAML map of command path -> docs.bronto.io URL")
	flag.Parse()
	if err := run(*out, *links); err != nil {
		fmt.Fprintln(os.Stderr, "docgen:", err)
		os.Exit(1)
	}
}

func run(outDir, linksFile string) error {
	// Flag defaults and help text must not depend on the generating
	// machine's environment.
	for _, kv := range os.Environ() {
		if k, _, _ := strings.Cut(kv, "="); strings.HasPrefix(k, "BRONTO_") {
			_ = os.Unsetenv(k)
		}
	}

	root := cli.NewRootCmd()
	root.InitDefaultHelpFlag()
	root.InitDefaultVersionFlag()
	root.InitDefaultCompletionCmd()

	learnMore, err := loadLinks(linksFile, root)
	if err != nil {
		return err
	}
	g := &gen{root: root, links: learnMore, norm: newNormalizer()}

	if err := os.MkdirAll(outDir, 0o755); err != nil { //nolint:gosec // committed docs directory, world-readable by design
		return err
	}
	// Remove previously generated pages so a deleted command's page goes
	// away instead of lingering.
	old, err := filepath.Glob(filepath.Join(outDir, "*.md"))
	if err != nil {
		return err
	}
	for _, f := range old {
		if err := os.Remove(f); err != nil {
			return err
		}
	}

	files := map[string]string{
		"index.md":              g.indexPage(),
		globalFlagsSlug + ".md": g.globalFlagsPage(),
	}
	for i, c := range topLevel(root) {
		files[c.Name()+".md"] = g.commandPage(c, i+2)
	}
	names := make([]string, 0, len(files))
	for n := range files {
		names = append(names, n)
	}
	sort.Strings(names)
	for _, n := range names {
		if err := os.WriteFile(filepath.Join(outDir, n), []byte(tidy(files[n])), 0o644); err != nil { //nolint:gosec // committed docs pages, world-readable by design
			return err
		}
	}
	fmt.Printf("docgen: wrote %d pages to %s\n", len(names), outDir)
	return nil
}

var blankRuns = regexp.MustCompile(`\n{3,}`)

// tidy collapses runs of blank lines and ends the page with one newline.
func tidy(page string) string {
	return strings.TrimRight(blankRuns.ReplaceAllString(page, "\n\n"), "\n") + "\n"
}

// topLevel returns the root's documented commands in cobra's sorted order.
func topLevel(root *cobra.Command) []*cobra.Command {
	var cmds []*cobra.Command
	for _, c := range root.Commands() {
		if c.IsAvailableCommand() {
			cmds = append(cmds, c)
		}
	}
	return cmds
}

// subcommands returns c's documented subcommands in cobra's sorted order.
func subcommands(c *cobra.Command) []*cobra.Command {
	var cmds []*cobra.Command
	for _, s := range c.Commands() {
		if s.IsAvailableCommand() {
			cmds = append(cmds, s)
		}
	}
	return cmds
}

// relPath is a command's path without the leading root name, the key used
// by reference-links.yaml (e.g. "datasets parser").
func relPath(c *cobra.Command) string {
	return strings.TrimPrefix(strings.TrimPrefix(c.CommandPath(), c.Root().Name()), " ")
}

func loadLinks(file string, root *cobra.Command) (map[string]string, error) {
	data, err := os.ReadFile(file) //nolint:gosec // path comes from the -links flag of a dev tool
	if err != nil {
		return nil, err
	}
	links := map[string]string{}
	if err := yaml.Unmarshal(data, &links); err != nil {
		return nil, fmt.Errorf("%s: %w", file, err)
	}
	var bad []string
	for k, v := range links {
		c, rest, err := root.Find(strings.Fields(k))
		if err != nil || c == root || len(rest) > 0 || relPath(c) != k || !c.IsAvailableCommand() {
			bad = append(bad, fmt.Sprintf("%q is not a documented command", k))
		}
		if !strings.HasPrefix(v, "https://docs.bronto.io/") {
			bad = append(bad, fmt.Sprintf("%q: link %q must be a https://docs.bronto.io/ URL", k, v))
		}
	}
	if len(bad) > 0 {
		sort.Strings(bad)
		return nil, fmt.Errorf("%s:\n  %s", file, strings.Join(bad, "\n  "))
	}
	return links, nil
}

// normalizer replaces machine-specific strings with stable placeholders.
type normalizer struct{ pairs []string }

func newNormalizer() *normalizer {
	type rep struct{ from, to string }
	var reps []rep
	add := func(from, to string) {
		if len(from) > 1 && from != "/" {
			reps = append(reps, rep{from, to})
		}
	}
	if d, err := os.UserConfigDir(); err == nil {
		add(d, "$XDG_CONFIG_HOME")
	}
	if d, err := os.UserCacheDir(); err == nil {
		add(d, "$XDG_CACHE_HOME")
	}
	if d, err := os.UserHomeDir(); err == nil {
		add(d, "~")
	}
	add(strings.TrimRight(os.TempDir(), "/"), "$TMPDIR")
	// Longest first so a config dir under $HOME wins over $HOME itself.
	sort.SliceStable(reps, func(i, j int) bool { return len(reps[i].from) > len(reps[j].from) })
	n := &normalizer{}
	for _, r := range reps {
		n.pairs = append(n.pairs, r.from, r.to)
	}
	return n
}

func (n *normalizer) s(v string) string {
	if len(n.pairs) == 0 {
		return v
	}
	return strings.NewReplacer(n.pairs...).Replace(v)
}

type gen struct {
	root  *cobra.Command
	links map[string]string
	norm  *normalizer
}

func frontmatter(b *bytes.Buffer, title, description, label string, order int) {
	b.WriteString("---\n")
	fmt.Fprintf(b, "title: %s\n", yamlString(title))
	fmt.Fprintf(b, "description: %s\n", yamlString(description))
	b.WriteString("editUrl: false\n")
	b.WriteString("sidebar:\n")
	fmt.Fprintf(b, "  label: %s\n", yamlString(label))
	fmt.Fprintf(b, "  order: %d\n", order)
	b.WriteString("---\n\n")
	b.WriteString(generatedNotice + "\n\n")
}

func yamlString(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	return `"` + s + `"`
}

// anchor reproduces Starlight's (github-slugger) heading id for a command
// heading: command paths are lowercase words separated by spaces.
func anchor(c *cobra.Command) string {
	return strings.ReplaceAll(strings.ToLower(c.CommandPath()), " ", "-")
}

// pageURL links to a command: its own page for a top-level command, an
// anchored section on the top-level page otherwise.
func pageURL(c *cobra.Command) string {
	top := c
	for top.HasParent() && top.Parent() != c.Root() {
		top = top.Parent()
	}
	if top == c {
		return urlBase + c.Name() + "/"
	}
	return urlBase + top.Name() + "/#" + anchor(c)
}

func (g *gen) indexPage() string {
	var b bytes.Buffer
	frontmatter(&b, "Command reference", "Every bronto command, subcommand, and flag, generated from the CLI itself.", "Overview", 0)
	b.WriteString("This reference is generated from the `bronto` command tree, so it always matches the binary built from the same commit. ")
	b.WriteString("Every command also accepts the [global flags](" + urlBase + globalFlagsSlug + "/). ")
	b.WriteString("Run `bronto <command> --help` for the same information in your terminal.\n\n")
	b.WriteString("| Command | Description |\n| --- | --- |\n")
	for _, c := range topLevel(g.root) {
		fmt.Fprintf(&b, "| [`%s`](%s) | %s |\n", c.CommandPath(), pageURL(c), cell(g.norm.s(c.Short)))
	}
	return b.String()
}

func (g *gen) globalFlagsPage() string {
	var b bytes.Buffer
	frontmatter(&b, "Global flags", "Flags every bronto command accepts.", "Global flags", 1)
	b.WriteString("These flags are defined on the root `bronto` command and are accepted by every subcommand.\n\n")
	g.flagTable(&b, g.root.PersistentFlags(), false)
	b.WriteString("\n## Root-only flags\n\n")
	b.WriteString("These flags apply to `bronto` itself. `-h`/`--help` also works on every subcommand.\n\n")
	g.flagTable(&b, g.root.LocalNonPersistentFlags(), true)
	return b.String()
}

func (g *gen) commandPage(c *cobra.Command, order int) string {
	var b bytes.Buffer
	frontmatter(&b, c.CommandPath(), g.norm.s(c.Short), c.Name(), order)
	g.commandBody(&b, c)

	var all []*cobra.Command
	var walk func(*cobra.Command)
	walk = func(p *cobra.Command) {
		for _, s := range subcommands(p) {
			all = append(all, s)
			walk(s)
		}
	}
	walk(c)
	for _, s := range all {
		fmt.Fprintf(&b, "\n## %s\n\n", s.CommandPath())
		g.commandBody(&b, s)
	}
	return b.String()
}

// commandBody renders one command: description, learn-more link, usage,
// aliases, subcommand table, flags, inherited flags, examples.
func (g *gen) commandBody(b *bytes.Buffer, c *cobra.Command) {
	desc := c.Long
	if strings.TrimSpace(desc) == "" {
		desc = c.Short
	}
	writeProse(b, g.norm.s(desc))

	if url, ok := g.links[relPath(c)]; ok {
		fmt.Fprintf(b, ":::tip[Learn more]\nThe Bronto docs explain the platform concept behind this command: [%s](%s)\n:::\n\n",
			strings.TrimPrefix(url, "https://"), url)
	}

	b.WriteString("```sh\n")
	if c.Runnable() {
		b.WriteString(g.norm.s(c.UseLine()) + "\n")
	}
	if c.HasAvailableSubCommands() {
		b.WriteString(c.CommandPath() + " <command> [flags]\n")
	}
	b.WriteString("```\n\n")

	if len(c.Aliases) > 0 {
		aliases := append([]string(nil), c.Aliases...)
		sort.Strings(aliases)
		b.WriteString("**Aliases:** ")
		for i, a := range aliases {
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(b, "`%s`", a)
		}
		b.WriteString("\n\n")
	}

	if subs := subcommands(c); len(subs) > 0 {
		b.WriteString("#### Subcommands\n\n| Command | Description |\n| --- | --- |\n")
		for _, s := range subs {
			fmt.Fprintf(b, "| [`%s`](%s) | %s |\n", s.CommandPath(), pageURL(s), cell(g.norm.s(s.Short)))
		}
		b.WriteString("\n")
	}

	if hasVisibleFlags(c.LocalFlags(), false) {
		b.WriteString("#### Flags\n\n")
		g.flagTable(b, c.LocalFlags(), false)
		b.WriteString("\n")
	}

	// Persistent flags inherited from a parent other than the root (the
	// root's are documented once, on the global-flags page).
	inherited := pflag.NewFlagSet("inherited", pflag.ContinueOnError)
	c.InheritedFlags().VisitAll(func(f *pflag.Flag) {
		if g.root.PersistentFlags().Lookup(f.Name) == nil {
			inherited.AddFlag(f)
		}
	})
	if hasVisibleFlags(inherited, false) {
		b.WriteString("#### Inherited flags\n\n")
		g.flagTable(b, inherited, false)
		b.WriteString("\n")
	}
	fmt.Fprintf(b, "Also accepts the [global flags](%s%s/).\n\n", urlBase, globalFlagsSlug)

	if ex := strings.TrimRight(c.Example, " \n\t"); ex != "" {
		b.WriteString("#### Examples\n\n```sh\n")
		b.WriteString(g.norm.s(dedent(ex)))
		b.WriteString("\n```\n")
	}
}

func hasVisibleFlags(fs *pflag.FlagSet, includeHelp bool) bool {
	found := false
	fs.VisitAll(func(f *pflag.Flag) {
		if !f.Hidden && f.Deprecated == "" && (includeHelp || f.Name != "help") {
			found = true
		}
	})
	return found
}

func (g *gen) flagTable(b *bytes.Buffer, fs *pflag.FlagSet, includeHelp bool) {
	b.WriteString("| Flag | Short | Type | Default | Description |\n| --- | --- | --- | --- | --- |\n")
	fs.VisitAll(func(f *pflag.Flag) {
		if f.Hidden || f.Deprecated != "" || (!includeHelp && f.Name == "help") {
			return
		}
		typ, usage := pflag.UnquoteUsage(f)
		if typ == "" {
			typ = f.Value.Type() // bool flags have no value name
		}
		short := ""
		if f.Shorthand != "" && f.ShorthandDeprecated == "" {
			short = "`-" + f.Shorthand + "`"
		}
		def := ""
		if d := g.norm.s(f.DefValue); !zeroDefault(f, d) {
			def = "`" + strings.ReplaceAll(d, "|", `\|`) + "`"
		}
		fmt.Fprintf(b, "| `--%s` | %s | %s | %s | %s |\n", f.Name, short, cell(typ), def, cell(g.norm.s(usage)))
	})
}

// zeroDefault mirrors pflag's own rule for omitting a default from help.
func zeroDefault(f *pflag.Flag, d string) bool {
	switch f.Value.Type() {
	case "bool":
		return d == "false"
	case "duration":
		return d == "0" || d == "0s"
	case "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64", "count", "float32", "float64":
		return d == "0"
	case "string":
		return d == ""
	case "stringSlice", "stringArray", "intSlice", "uintSlice", "boolSlice", "durationSlice", "float64Slice", "float32Slice", "int32Slice", "int64Slice":
		return d == "[]"
	}
	return d == "" || d == "<nil>" || d == "[]" || d == "map[]"
}

// writeProse renders help text as Markdown paragraphs. Help text is plain
// text, so Markdown/HTML metacharacters are escaped; a paragraph with
// indented lines is preformatted and kept verbatim in a text block.
func writeProse(b *bytes.Buffer, text string) {
	for _, para := range strings.Split(strings.TrimSpace(text), "\n\n") {
		para = strings.Trim(para, "\n")
		if para == "" {
			continue
		}
		pre := false
		for _, l := range strings.Split(para, "\n") {
			if strings.HasPrefix(l, " ") || strings.HasPrefix(l, "\t") {
				pre = true
			}
		}
		if pre {
			b.WriteString("```text\n" + dedent(para) + "\n```\n\n")
			continue
		}
		b.WriteString(escape(para) + "\n\n")
	}
}

var mdEscaper = strings.NewReplacer(
	`\`, `\\`, `<`, `&lt;`, `>`, `&gt;`, `*`, `\*`, `_`, `\_`, `[`, `\[`, `]`, `\]`, "`", "\\`", "{", "&#123;", "}", "&#125;",
)

func escape(s string) string { return mdEscaper.Replace(s) }

// cell escapes text for a GFM table cell.
func cell(s string) string {
	return strings.ReplaceAll(escape(strings.Join(strings.Fields(s), " ")), "|", `\|`)
}

// dedent strips the common leading whitespace of non-blank lines.
func dedent(s string) string {
	lines := strings.Split(s, "\n")
	prefix := -1
	for _, l := range lines {
		if strings.TrimSpace(l) == "" {
			continue
		}
		n := len(l) - len(strings.TrimLeft(l, " \t"))
		if prefix < 0 || n < prefix {
			prefix = n
		}
	}
	for i, l := range lines {
		if len(l) >= prefix && prefix > 0 {
			lines[i] = l[prefix:]
		} else {
			lines[i] = strings.TrimLeft(l, " \t")
		}
		lines[i] = strings.TrimRight(lines[i], " \t")
	}
	return strings.Join(lines, "\n")
}
