package cli

import (
	"strings"
	"testing"

	"github.com/spf13/cobra"
)

func TestEndpointInventoryShape(t *testing.T) {
	inv := EndpointInventory()
	byPattern := map[string]string{}
	for _, e := range inv {
		if e.Pattern == "" || e.Command == "" {
			t.Fatalf("inventory entry with empty field: %+v", e)
		}
		if _, dup := byPattern[e.Pattern]; dup {
			t.Fatalf("duplicate pattern %q — commands must merge into one entry", e.Pattern)
		}
		byPattern[e.Pattern] = e.Command
	}

	// Registry expansion: every resource contributes its Base, and a per-ID
	// pattern unless it is list-only.
	for _, d := range resourceRegistry {
		if byPattern[d.Base] == "" {
			t.Errorf("registry Base %q missing from inventory", d.Base)
		}
		if d.NoGet && d.NoUpdate && d.NoDelete {
			continue
		}
		if byPattern[d.idBase()+"/{*}"] == "" {
			t.Errorf("registry per-ID pattern %q missing from inventory", d.idBase()+"/{*}")
		}
	}

	// A pattern shared by several commands merges (e.g. /logs is datasets'
	// Base and ping's health-check endpoint).
	if c := byPattern["/logs"]; !strings.Contains(c, "datasets") || !strings.Contains(c, "ping") {
		t.Errorf("/logs command = %q, want both datasets and ping", c)
	}
}

// commandsWithoutSpecEndpoints lists leaf commands that call no endpoint in
// api/openapi.yaml, with the reason. Everything else must be generated by
// resourceRegistry or named in handWrittenEndpoints.
var commandsWithoutSpecEndpoints = map[string]string{
	"bronto api":            "generic passthrough to any path",
	"bronto auth logout":    "local credential store only",
	"bronto auth switch":    "local credential store only",
	"bronto auth token":     "local credential store only",
	"bronto config":         "local config file only (all subcommands)",
	"bronto version":        "local build info",
	"bronto plugins":        "scans PATH for bronto-* executables (all subcommands)",
	"bronto query check":    "local query parser",
	"bronto monitors check": "local monitor lint",
	"bronto send":           "ingestion host, a separate API not described by the spec",
}

// inventoryCommands expands handWrittenEndpoints' Command strings into full
// command paths: "bronto search / tail" → "bronto search", "bronto tail".
func inventoryCommands() []string {
	var out []string
	for _, e := range handWrittenEndpoints {
		for _, c := range strings.Split(e.Command, " / ") {
			if !strings.HasPrefix(c, "bronto ") {
				c = "bronto " + c
			}
			out = append(out, c)
		}
	}
	return out
}

// TestEveryCommandIsInventoried is the guard for #121: groups members and
// the users verb-actions shipped without inventory entries, so spec-sync
// reported their endpoints as having "no CLI coverage". Every leaf command
// must be registry-generated, named in handWrittenEndpoints, or declared in
// commandsWithoutSpecEndpoints.
func TestEveryCommandIsInventoried(t *testing.T) {
	covered := func(path string, names []string) bool {
		for _, n := range names {
			if path == n || strings.HasPrefix(path, n+" ") {
				return true
			}
		}
		return false
	}
	generated := map[string]bool{}
	for _, d := range resourceRegistry {
		for _, verb := range []string{"list", "get", "create", "update", "delete"} {
			generated["bronto "+d.display()+" "+verb] = true
		}
	}
	inventoried := inventoryCommands()
	var exempt []string
	for c := range commandsWithoutSpecEndpoints {
		exempt = append(exempt, c)
	}

	var walk func(c *cobra.Command)
	walk = func(c *cobra.Command) {
		for _, sub := range c.Commands() {
			if sub.Hidden || sub.Name() == "help" {
				continue
			}
			walk(sub)
		}
		if c.HasSubCommands() || !c.Runnable() {
			return
		}
		path := c.CommandPath()
		if generated[path] || covered(path, inventoried) || covered(path, exempt) {
			return
		}
		t.Errorf("%s calls no inventoried endpoint: add its paths to handWrittenEndpoints, "+
			"or to commandsWithoutSpecEndpoints if it calls none in the spec", path)
	}
	walk(NewRootCmd())

	// Stale entries are as misleading as missing ones.
	for _, c := range append(inventoried, exempt...) {
		if cmd, _, err := NewRootCmd().Find(strings.Fields(c)[1:]); err != nil || cmd.CommandPath() != c {
			t.Errorf("inventory names %q, which is not a command", c)
		}
	}
}
