// Code generated by scripts/logo2frames.py from assets/logomark.png. DO NOT EDIT.
//
// The rendered figure is the Bronto logo, a trademark used with permission
// (see TRADEMARK.md); it is NOT covered by this repository's MIT license.

package cli

// mascotFrame is the classified logo grid: each rune is a cell kind —
// ' ' background, 'y' bright hide, 'o' darker facet, 'k' outline.
var mascotFrame = []string{
	"                                                 k",
	"                                              kkkookkkk",
	"                                             kkoyyyyyoookkk",
	"                                            kkyyyyyyyyyyyyokk",
	"                                           kkyyyyyyyyyyyyyok",
	"                                          kkoyyyyyokkkkkkkk",
	"                                          koyyyyyyok",
	"                                         kkyyyyyyyok",
	"                               kkkkkkkkkkkyyyyyyyykk",
	"                             kkooyyyyyyyyyyyyyyyyykk",
	"                           kkkyyyyyyyyyyyyyyyyyyyykk",
	"                         kkoooooyyyyyyyyyyyyyyyyyykk",
	"                      kkkoyyyyyoooyyyyyyyyyyyyyyyokk",
	"                    kkoooyyyyyyyyoooyyyyyyyyyyyookk",
	"                 kkooyyyooyyyyyyyyooyyyyyyyyyooookk",
	"               kkoyyyyyyykoyyyyyooyyyyyyyyyyoooookk",
	"            kkooyyyyyyyyyykyyyyokooooooyyyyooooookk",
	"          kkoyyyyyyyyyoookkoyyykooookkkyyyyooooookk",
	"       kkoyyyyyoookkkkkk  koyyykooookkkyyyyokooook",
	"     kkoooookkkkk         koyyykooookkkyyyyokooook",
	"  kkkkkkk                 kkkkkkkkkkkkkkkkkkkkkkkk",
	"",
}
