// Code generated by scripts/logo2frames.py from assets/logomark.png. DO NOT EDIT.
//
// The rendered figure is the Bronto logo, a trademark used with permission
// (see TRADEMARK.md); it is NOT covered by this repository's MIT license.

package cli

// mascotFrame is the classified logo grid (full size, graze/herd): each
// rune is a cell kind — ' ' background, 'y' bright hide, 'o' facet, 'k' outline.
var mascotFrame = []string{
	"                                                 k",
	"                                              kkkookkkk",
	"                                             kkoyyyyyoookkk",
	"                                            kkyyyyyyyyyyyyokk",
	"                                           kkyyyyyyyyyyyyyok",
	"                                          kkoyyyyyokkkkkkkk",
	"                                          koyyyyyyok",
	"                                         kkyyyyyyyok",
	"                               kkkkkkkkkkkyyyyyyyykk",
	"                             kkooyyyyyyyyyyyyyyyyykk",
	"                           kkkyyyyyyyyyyyyyyyyyyyykk",
	"                         kkoooooyyyyyyyyyyyyyyyyyykk",
	"                      kkkoyyyyyoooyyyyyyyyyyyyyyyokk",
	"                    kkoooyyyyyyyyoooyyyyyyyyyyyookk",
	"                 kkooyyyooyyyyyyyyooyyyyyyyyyooookk",
	"               kkoyyyyyyykoyyyyyooyyyyyyyyyyoooookk",
	"            kkooyyyyyyyyyykyyyyokooooooyyyyooooookk",
	"          kkoyyyyyyyyyoookkoyyykooookkkyyyyooooookk",
	"       kkoyyyyyoookkkkkk  koyyykooookkkyyyyokooook",
	"     kkoooookkkkk         koyyykooookkkyyyyokooook",
	"  kkkkkkk                 kkkkkkkkkkkkkkkkkkkkkkkk",
	"",
}

// mascotFrameSmall is the compact grid used by rumble's speech bubble.
var mascotFrameSmall = []string{
	"                               kk",
	"                             koooookk",
	"                            koyyyyyyyok",
	"                           kkyyyyooook",
	"                           kyyyyok",
	"                         kkoyyyyok",
	"                   koooooooyyyyykk",
	"                kkooyyyyyyyyyyyyk",
	"              kkoyyyooyyyyyyyyyok",
	"            koyooyyyyyoyyyyyyyook",
	"         kkoyyyyoyyyyoyyyyyyooook",
	"       kooyyyyyyooyyoookkyyyooook",
	"     ooyyooookkkkoyyoookkyyykook",
	"  kkkookk        kookookkoookook",
	"",
}

// mascotFrameTiny is the tiny grid used by the herd "rain".
var mascotFrameTiny = []string{
	"                    oo",
	"                  koyyook",
	"                 koyykoo",
	"            koooooyyyk",
	"         oooyyyyyyyyok",
	"      ooyyoyyoooyyook",
	"   oooooookoyookoyook",
	"           koko koko",
}
