import { defineRouteMiddleware, type StarlightRouteData } from '@astrojs/starlight/route-data';

// Autogenerated sidebar groups take their label from the directory name.
// Give the generated command reference (reference/commands/) a proper label.
const labels: Record<string, string> = { commands: 'Commands' };

type Entry = StarlightRouteData['sidebar'][number];

function relabel(entries: Entry[]): void {
	for (const entry of entries) {
		if (entry.type === 'group') {
			entry.label = labels[entry.label] ?? entry.label;
			relabel(entry.entries);
		}
	}
}

export const onRequest = defineRouteMiddleware((context) => {
	relabel(context.locals.starlightRoute.sidebar);
});
