#!/usr/bin/env bash
# docs-required.sh — fail a PR that changes user-facing CLI code without
# touching the hand-written docs.
#
# The generated command reference (make docs-reference) keeps flags and help
# text in sync automatically, but it cannot explain WHY or WHEN to use a
# command. So a PR that changes CLI behavior must also touch a guide (or
# skill.md, the agent-facing doc) — or say explicitly that no docs are
# needed by carrying the `no-docs-needed` label.
#
# Inputs (environment):
#   BASE_SHA    base commit of the PR (required)
#   HEAD_SHA    head commit of the PR (required)
#   PR_LABELS   comma-separated PR label names (optional)
#
# Exit status: 0 = ok (docs touched, nothing user-facing changed, or the
# override label is present); 1 = docs required; 2 = usage error.
#
# Usage:
#   BASE_SHA=... HEAD_SHA=... PR_LABELS=a,b scripts/docs-required.sh
#   scripts/docs-required.sh --self-test   prove the gate goes both red and
#                                          green, using a throwaway git repo
set -euo pipefail

# --- What counts as user-facing CLI code (extended regexes, repo-relative).
# Non-test Go files under these paths change what users see or do.
USER_FACING_CODE=(
  '^internal/cli/.*\.go$'
  '^cmd/bronto/.*\.go$'
  '^internal/output/.*\.go$'
  '^internal/config/.*\.go$'
)
# Excluded even when they match above: tests, and generated/embedded art.
NOT_USER_FACING=(
  '_test\.go$'
  '^internal/cli/mascot_frames\.go$'
)
# --- What counts as hand-written docs.
DOCS_PATHS=(
  '^docs/src/content/docs/.*\.mdx?$'
  '^skill\.md$'
)
# Generated docs do not count (they change automatically with the code).
NOT_DOCS=(
  '^docs/src/content/docs/reference/commands/'
)
OVERRIDE_LABEL=no-docs-needed

# join_re builds one alternation regex from an array.
join_re() {
  local IFS='|'
  printf '(%s)' "$*"
}

# check BASE HEAD LABELS — run from inside the git repo to inspect.
check() {
  local base=$1 head=$2 labels=$3

  local label
  IFS=',' read -r -a label_list <<< "$labels"
  for label in "${label_list[@]+"${label_list[@]}"}"; do
    label=$(printf '%s' "$label" | tr -d '[:space:]')
    if [ "$label" = "$OVERRIDE_LABEL" ]; then
      echo "docs-required: '$OVERRIDE_LABEL' label present — skipping the docs check."
      return 0
    fi
  done

  local changed
  if ! changed=$(git diff --name-only --no-renames "$base" "$head" --); then
    echo "docs-required: git diff $base..$head failed (are both commits fetched? use fetch-depth: 0)" >&2
    return 2
  fi

  local code docs
  code=$(printf '%s\n' "$changed" | grep -E "$(join_re "${USER_FACING_CODE[@]}")" \
    | grep -vE "$(join_re "${NOT_USER_FACING[@]}")" || true)
  docs=$(printf '%s\n' "$changed" | grep -E "$(join_re "${DOCS_PATHS[@]}")" \
    | grep -vE "$(join_re "${NOT_DOCS[@]}")" || true)

  if [ -z "$code" ]; then
    echo "docs-required: no user-facing CLI code changed — ok."
    return 0
  fi
  if [ -n "$docs" ]; then
    echo "docs-required: user-facing code changed and docs were updated — ok."
    printf '%s\n' "$docs" | sed 's/^/  docs: /'
    return 0
  fi

  cat >&2 <<EOF
docs-required: this PR changes user-facing CLI code but no hand-written docs.

Changed user-facing files:
$(printf '%s\n' "$code" | sed 's/^/  /')

How to fix — pick one:
  1. Update the guide that covers this behavior under
     docs/src/content/docs/ (not reference/commands/, which is generated by
     'make docs-reference'), and/or skill.md for agent-facing changes.
     Not sure where? 'make docs-coverage' lists commands no guide teaches yet.
  2. If nothing a user could notice changed (refactor, internal fix, error
     text polish already covered by the reference), add the
     '$OVERRIDE_LABEL' label to the PR and re-run this check.
EOF
  return 1
}

self_test() {
  self_test_tmp=$(mktemp -d)
  trap 'rm -rf "$self_test_tmp"' EXIT
  local tmp=$self_test_tmp
  (
    set -e
    cd "$tmp"
    git init -q
    git config user.email docs-required@example.com
    git config user.name docs-required-self-test
    git config commit.gpgsign false
    git config core.hooksPath /dev/null
    mkdir -p internal/cli docs/src/content/docs/guides docs/src/content/docs/reference/commands
    echo 'package cli' > internal/cli/x.go
    git add -A && git commit -qm base
    base=$(git rev-parse HEAD)

    # 1. Code change, no docs -> red.
    echo '// change' >> internal/cli/x.go
    git commit -qam code-only
    code_only=$(git rev-parse HEAD)
    if check "$base" "$code_only" "" >/dev/null 2>&1; then
      echo "docs-required: SELF-TEST FAILED — a code-only change passed (gate cannot go red)" >&2
      exit 1
    fi
    # 2. Same change with the override label -> green.
    check "$base" "$code_only" "bug, no-docs-needed ,ci" >/dev/null 2>&1 || {
      echo "docs-required: SELF-TEST FAILED — '$OVERRIDE_LABEL' label did not pass" >&2; exit 1; }
    # 3. Regenerated reference alone does not count as docs -> red.
    echo 'ref' > docs/src/content/docs/reference/commands/x.md
    git add -A && git commit -qm ref-only
    if check "$base" "$(git rev-parse HEAD)" "" >/dev/null 2>&1; then
      echo "docs-required: SELF-TEST FAILED — a generated-reference-only change counted as docs" >&2
      exit 1
    fi
    # 4. Code + guide -> green.
    echo '# guide' > docs/src/content/docs/guides/x.mdx
    git add -A && git commit -qm guide
    check "$base" "$(git rev-parse HEAD)" "" >/dev/null 2>&1 || {
      echo "docs-required: SELF-TEST FAILED — code + guide change did not pass" >&2; exit 1; }
    # 5. Tests only -> green.
    git checkout -q "$base"
    echo 'package cli' > internal/cli/x_test.go
    git add -A && git commit -qm test-only
    check "$base" "$(git rev-parse HEAD)" "" >/dev/null 2>&1 || {
      echo "docs-required: SELF-TEST FAILED — a test-only change was flagged" >&2; exit 1; }
  ) || exit 1
  echo "docs-required: self-test ok (red: code-only, reference-only; green: label, guide, test-only)"
}

if [ "${1:-}" = "--self-test" ]; then
  self_test
  exit 0
fi

if [ -z "${BASE_SHA:-}" ] || [ -z "${HEAD_SHA:-}" ]; then
  echo "docs-required: BASE_SHA and HEAD_SHA must be set (PR_LABELS optional, comma-separated)" >&2
  exit 2
fi
cd "$(dirname "$0")/.."
check "$BASE_SHA" "$HEAD_SHA" "${PR_LABELS:-}"
