#!/usr/bin/env python3
"""Generate the ASCII mascot frames from the Bronto logo.

Traces assets/logomark.png down to a character grid and writes
internal/cli/mascot_frames.go. Each cell is classified into one of four
kinds — space / hide / facet / outline — and the Go renderer colors them
at runtime (truecolor) or falls back to ink-density glyphs (NO_COLOR).

The logo is a Bronto trademark used with permission (see TRADEMARK.md);
it is NOT covered by the repo's MIT license. Regenerate, never hand-edit
the output:

    python3 scripts/logo2frames.py

Requires macOS `sips` (used to downscale + convert to BMP so the script
has zero third-party deps). On other platforms, pre-convert the logo to a
small 24/32-bit BMP and pass it as the first argument.
"""
import os
import struct
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "assets", "logomark.png")
OUT = os.path.join(ROOT, "internal", "cli", "mascot_frames.go")
COLS, ROWS = 62, 22          # full grid — graze
COLS_SM, ROWS_SM = 40, 15    # compact grid — rumble's cowsay bubble
COLS_TINY, ROWS_TINY = 26, 10  # tiny grid — the herd "rain" (proper aspect)


def to_bmp(png, cols, rows):
    """Downscale the PNG to cols×rows and emit a BMP via macOS sips."""
    tmp = tempfile.mkdtemp()
    small = os.path.join(tmp, "small.png")
    bmp = os.path.join(tmp, "small.bmp")
    subprocess.run(["sips", "-z", str(rows), str(cols), png, "--out", small],
                   check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    subprocess.run(["sips", "-s", "format", "bmp", small, "--out", bmp],
                   check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    return bmp


def read_bmp(path):
    with open(path, "rb") as f:
        d = f.read()
    off = struct.unpack("<I", d[10:14])[0]
    w = struct.unpack("<i", d[18:22])[0]
    h = struct.unpack("<i", d[22:26])[0]
    bpp = struct.unpack("<H", d[28:30])[0]
    stride = ((w * bpp // 8) + 3) // 4 * 4
    rows = []
    for y in range(abs(h)):
        row = []
        base = off + y * stride
        for x in range(w):
            i = base + x * (bpp // 8)
            b, g, r = d[i], d[i + 1], d[i + 2]
            a = d[i + 3] if bpp == 32 else 255
            row.append((r, g, b, a))
        rows.append(row)
    if h > 0:
        rows.reverse()
    return rows


def classify(px):
    r, g, b, a = px
    if a < 80:
        return " "          # transparent background
    if r < 90 and g < 90:
        return "k"          # black outline
    if r > 200 and g > 160:
        return "y"          # bright hide
    return "o"              # darker facet


def grid(cols, rows_n):
    """Classify the logo downscaled to cols×rows_n into rstripped lines."""
    bmp = to_bmp(SRC, cols, rows_n)
    return ["".join(classify(px) for px in row).rstrip() for row in read_bmp(bmp)]


def emit_var(body, name, doc, lines):
    body.append(doc)
    body.append("var " + name + " = []string{")
    for line in lines:
        body.append("\t" + gostr(line) + ",")
    body.append("}")
    body.append("")


def main():
    if len(sys.argv) > 1:  # pre-converted BMP → single (full) frame only
        lines = ["".join(classify(px) for px in row).rstrip() for row in read_bmp(sys.argv[1])]
        small = lines
    else:
        lines = grid(COLS, ROWS)
        small = grid(COLS_SM, ROWS_SM)
        tiny = grid(COLS_TINY, ROWS_TINY)

    body = [
        "// Code generated by scripts/logo2frames.py from assets/logomark.png. DO NOT EDIT.",
        "//",
        "// The rendered figure is the Bronto logo, a trademark used with permission",
        "// (see TRADEMARK.md); it is NOT covered by this repository's MIT license.",
        "",
        "package cli",
        "",
    ]
    emit_var(body,
             "mascotFrame",
             "// mascotFrame is the classified logo grid (full size, graze/herd): each\n"
             "// rune is a cell kind — ' ' background, 'y' bright hide, 'o' facet, 'k' outline.",
             lines)
    emit_var(body,
             "mascotFrameSmall",
             "// mascotFrameSmall is the compact grid used by rumble's speech bubble.",
             small)
    if len(sys.argv) <= 1:
        emit_var(body,
                 "mascotFrameTiny",
                 "// mascotFrameTiny is the tiny grid used by the herd \"rain\".",
                 tiny)

    with open(OUT, "w") as f:
        f.write("\n".join(body))
    print(f"wrote {OUT} (full {len(lines)} rows, small {len(small)} rows)")


def gostr(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


if __name__ == "__main__":
    main()
