#!/usr/bin/env python3
"""Generate the ASCII mascot frames from the Bronto logo.

Traces assets/logomark.png down to a character grid and writes
internal/cli/mascot_frames.go. Each cell is classified into one of four
kinds — space / hide / facet / outline — and the Go renderer colors them
at runtime (truecolor) or falls back to ink-density glyphs (NO_COLOR).

The logo is a Bronto trademark used with permission (see TRADEMARK.md);
it is NOT covered by the repo's MIT license. Regenerate, never hand-edit
the output:

    python3 scripts/logo2frames.py

Requires macOS `sips` (used to downscale + convert to BMP so the script
has zero third-party deps). On other platforms, pre-convert the logo to a
small 24/32-bit BMP and pass it as the first argument.
"""
import os
import struct
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "assets", "logomark.png")
OUT = os.path.join(ROOT, "internal", "cli", "mascot_frames.go")
COLS, ROWS = 62, 22  # character grid; sauropod reads well at this size


def to_bmp(png, cols, rows):
    """Downscale the PNG to cols×rows and emit a BMP via macOS sips."""
    tmp = tempfile.mkdtemp()
    small = os.path.join(tmp, "small.png")
    bmp = os.path.join(tmp, "small.bmp")
    subprocess.run(["sips", "-z", str(rows), str(cols), png, "--out", small],
                   check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    subprocess.run(["sips", "-s", "format", "bmp", small, "--out", bmp],
                   check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    return bmp


def read_bmp(path):
    with open(path, "rb") as f:
        d = f.read()
    off = struct.unpack("<I", d[10:14])[0]
    w = struct.unpack("<i", d[18:22])[0]
    h = struct.unpack("<i", d[22:26])[0]
    bpp = struct.unpack("<H", d[28:30])[0]
    stride = ((w * bpp // 8) + 3) // 4 * 4
    rows = []
    for y in range(abs(h)):
        row = []
        base = off + y * stride
        for x in range(w):
            i = base + x * (bpp // 8)
            b, g, r = d[i], d[i + 1], d[i + 2]
            a = d[i + 3] if bpp == 32 else 255
            row.append((r, g, b, a))
        rows.append(row)
    if h > 0:
        rows.reverse()
    return rows


def classify(px):
    r, g, b, a = px
    if a < 80:
        return " "          # transparent background
    if r < 90 and g < 90:
        return "k"          # black outline
    if r > 200 and g > 160:
        return "y"          # bright hide
    return "o"              # darker facet


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else to_bmp(SRC, COLS, ROWS)
    rows = read_bmp(src)
    lines = ["".join(classify(px) for px in row).rstrip() for row in rows]

    body = [
        "// Code generated by scripts/logo2frames.py from assets/logomark.png. DO NOT EDIT.",
        "//",
        "// The rendered figure is the Bronto logo, a trademark used with permission",
        "// (see TRADEMARK.md); it is NOT covered by this repository's MIT license.",
        "",
        "package cli",
        "",
        "// mascotFrame is the classified logo grid: each rune is a cell kind —",
        "// ' ' background, 'y' bright hide, 'o' darker facet, 'k' outline.",
        "var mascotFrame = []string{",
    ]
    for line in lines:
        body.append("\t" + gostr(line) + ",")
    body.append("}")
    body.append("")

    with open(OUT, "w") as f:
        f.write("\n".join(body))
    print(f"wrote {OUT} ({len(lines)} rows)")


def gostr(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


if __name__ == "__main__":
    main()
